if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" PLUGINS
Plug 'airblade/vim-gitgutter'
Plug 'ggreer/the_silver_searcher'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-plug'
Plug 'justinmk/vim-sneak'
Plug 'mattn/emmet-vim'
Plug 'mattn/webapi-vim'
Plug 'mileszs/ack.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tomtom/tcomment_vim'

" APPEARANCE AND THEMES 
Plug 'arcticicestudio/nord-vim'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'drewtempelmeyer/palenight.vim'
Plug 'itchyny/lightline.vim'
Plug 'joshdick/onedark.vim'
Plug 'miyakogi/seiya.vim'
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-scripts/xoria256.vim'
Plug 'Xuyuanp/nerdtree-git-plugin'

call plug#end()

" CONFIG
syntax on
filetype plugin on
filetype indent on
set autoindent
set backspace=indent,eol,start
set cmdheight=2
set cindent
set colorcolumn=+1
set expandtab
set encoding=utf-8
set fileformats=unix,dos,mac
set foldcolumn=2
set hidden
set nohlsearch
set incsearch
set lazyredraw
set list
set listchars=tab:▷⋅,trail:⋅,nbsp:⋅
set magic
set mouse=a
set nobackup
set noerrorbells
set nospell spelllang=en_us
set noswapfile
set novisualbell
set nowb
set nowrap
set nowritebackup
set number
set path+=$PWD/**
set rnu
set scrolloff=10
set signcolumn=yes
set shiftwidth=2
set showmatch
set shortmess+=c
set softtabstop=0
set tabstop=2
set textwidth=999
set tm=500
set updatetime=300
set vb t_vb=
set wrapmargin=0
set wildmenu
set wildignore+=*/tmp/*,*.so,*.swp,*.zip

let mapleader=" "
let g:dracula_italic=0
colorscheme dracula
set background=dark
scriptencoding utf-8

let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1

" AIRLINE
let g:airline_powerline_fonts=1

" SPLIT NAVIGATION
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" TABS
nnoremap tn :tabnew<Space>
nnoremap tk :tabnext<CR>
nnoremap tj :tabprev<CR>
nnoremap th :tabfirst<CR>
nnoremap tl :tablast<CR>
nnoremap tc :tabclose<CR>

" TOGGLE HIGHLIGHT SEARCH
nnoremap <F4> :set hlsearch!<CR>

" ALACRITTY
" TRANSPARENCY FIX
hi! Normal ctermbg=NONE guibg=NONE
hi! NonText ctermbg=NONE guibg=NONE guifg=NONE ctermfg=NONE
"
let g:fzf_preview_window = 'right:60%'
let $FZF_DEFAULT_COMMAND = 'ag --hidden --ignore .git -l -g ""'

" FZF FILES WITH PREVIEW
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, 
    \ fzf#vim#with_preview(), 
    \ <bang>0)

" FZF AG WITH PREVIEW
" DEFAULT OPTIONS --nogroup --column --color
let s:ag_options = ' --one-device --skip-vcs-ignores --smart-case '

command! -bang -nargs=* Ag
   \ call fzf#vim#ag(<q-args>,
   \ fzf#vim#with_preview(), 
   \ <bang>0)
"
" THIS IS THE DEFAULT EXTRA KEY BINDINGS
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
let g:fzf_buffers_jump=1

" HIDE STATUSLINE
autocmd! FileType fzf set laststatus=0 noshowmode noruler
  \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler

" CUSTOM STATUSLINE
function! s:fzf_statusline()
    highlight fzf1 ctermfg=161 ctermbg=251
    highlight fzf2 ctermfg=23 ctermbg=251
    highlight fzf3 ctermfg=237 ctermbg=251
    setlocal statusline=%#fzf1#\ >\ %#fzf2#fz%#fzf3#f
  endfunction

  autocmd! User FzfStatusLine call <SID>fzf_statusline()

" FUNCTION KEYBINDINGS
nmap <C-F> :Files<cr>
nmap <C-I> :Ag<cr>
vmap <C-G> <Esc><Esc>:GFiles?<cr>
inoremap <C-F> <Esc><Esc>:BLines<cr>

" COC 
" USE TAB FOR TRIGGER COMPLETION WITH CHARACTERS AHEAD AND NAVIGATE.
" NOTE: USE COMMAND ':verbose imap <tab>' TO MAKE SURE TAB IS NOT MAPPED BY
" OTHER PLUGIN BEFORE PUTTING THIS INTO YOUR CONFIG.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
"
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
"
" GOTO CODE NAVIGATION.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
"
:nmap <space>e :CocCommand explorer<CR>
" EXPLORER
nmap <space>e :CocCommand explorer<CR>
nmap <space>f :CocCommand explorer --preset floating<CR>
autocmd BufEnter * if (winnr("$") == 1 && &filetype == 'coc-explorer') | q | endif
"
" USE PRESET ARGUMENT TO OPEN IT
nmap <space>ed :CocCommand explorer --preset .vim<CR>
"
" USE K TO SHOW DOCUMENTATION IN PREVIEW WINDOW.
nnoremap <silent> K :call <SID>show_documentation()<CR>
"
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
" HIGHLIGHT THE SYMBOL AND ITS REFERENCES WHEN HOLDING THE CURSOR.
autocmd CursorHold * silent call CocActionAsync('highlight')

" GLOBAL EXTENSIONS
let g:coc_global_extions = [
\ 'coc-pairs',
\ 'coc-explorer',
\ 'coc-git',
\ 'coc-highlight',
\ 'coc-template',
\ 'coc-snippets',
\ 'coc-ultisnips',
\ 'coc-lists',
\ 'coc-prettier',
\ 'coc-eslint',
\ 'coc-tslint',
\ 'coc-tslint-plugin',
\ 'coc-sh',
\ 'coc-vimlsp',
\ 'coc-emmet',
\ 'coc-phpls',
\ 'coc-markdownlint',
\ 'coc-json',
\ 'coc-svg',
\ 'coc-html',
\ 'coc-tsserver',
\ 'coc-vetur',
\ 'coc-css',
\ 'coc-yaml'
\ ]

" EMMET
" ENABLE EMMET ONLY IN HTML/CSS FILES
let g:user_emmet_mode='n'
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall


" NERDTREE VIM-DEVICONS
let g:NERDTreeGitStatusIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
    \ }
" OPEN SHORTCUT

" NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" SHOW HIDDEN FILES
let NERDTreeShowHidden=1
let g:NERDTreeMouseMode = 2
let g:NERDTreeWinSize = 40
let g:NRDTreeMinimalUI=1
let g:NERDTreeIgnore=['\v[\/]\.(git|hg|svn)$']

map <C-n> :NERDTreeToggle<CR>

" SIEYA
" CLEAR AND MAKE TRANSPARENT BACKGROUND COLOR IN (TRANSPARENT) TERMINAL
let g:seiya_auto_enable=1

" INDENT NEXT LINE LIKE NORMAL IDE
imap <C-Return> <CR><CR><C-o>k<Tab>

" CMD+X / CMD+C COPY TO CLIPBOARD
vmap <C-x> :!pbcopy<CR>
vmap <C-c> :w !pbcopy<CR><CR>

" GOTO MATCHING TAG/BRACKETS
runtime macros/matchit.vim
"
" JUMP MATCHING OPENING/CLOSING
noremap % v%

" DISABLE ARROW KEYS AND USE UP AND DOWN FOR MOVING SELECTED / LINE OF CODES
no  <down>  mz:m+<CR>`z
no  <left>  <Nop>
no  <right> <Nop>
no  <up>    mz:m-2<CR>`z
ino <down>  <Esc><Esc>mz:m+<CR>`z
ino <left>  <Nop>
ino <right> <Nop>
ino <up>    <Esc><Esc>mz:m-2<CR>`z
vno <down>  :m'>+<CR>`<my`>mzgv`yo`z
vno <left>  <Nop>
vno <right> <Nop>
vno <up>    :m'<-2<CR>`>my`<mzgv`yo`z

" SNEAK
let g:sneak#label=1

nnoremap <Leader>ev :tabnew $MYVIMRC<CR>
nmap <Leader>gs :G<CR>
nmap <Leader>gc :Gcommit<CR>
nmap <Leader>gp :Gpush<CR>
nmap <Leader>gj :diffget //3<CR>
nmap <Leader>gf :diffget //2<CR>
