###t-ns-completion-start-###
if [ -f /Users/regene/.tnsrc ]; then 
    source /Users/regene/.tnsrc 
fi
###-tns-completion-end-###

fpath+=${ZDOTDIR:-~}/.zsh_functions
autoload -U compinit 

# LOAD CUSTOM SCRIPTS
for f in ~/.zsh_functions/[0-9]*.(sh|zsh)
do
	source "$f"
done
