export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

###t-ns-completion-start-###
if [ -f /Users/regene/.tnsrc ]; then 
    source /Users/regene/.tnsrc 
fi
###-tns-completion-end-###

fpath+=${ZDOTDIR:-~}/.zsh_functions
autoload -U compinit fzf-git-branch fzf-git-checkout

export FZF_DEFAULT_OPTS='--height 40% --preview-window right:60% --layout=reverse --border'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -l -g'

# ALIAS
alias cls=clear
alias gb='fzf-git-branch'
alias gco='fzf-git-checkout'
